language: ruby
cache: bundler

rvm:
  - 2.3.0

services:
  - redis-server

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never
