web:
  build: .
  command: run
  ports:
    - "5000:5000"
  links:
    - postgres
  volumes:
    - .:/rw_adapter_cartodb

web:
  build: .
  command: run
  ports:
    - "5000:5000"
  links:
    - postgres
  volumes:
    - .:/rw_adapter_cartodb
postgres:
  image: postgres
  container_name: rw_adapter_cartodb-postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=resource_watch_development
